spring.application.name=spring-webflux
spring.r2dbc.url=r2dbc:h2:mem:///testPersonas
spring.r2dbc.name=sa
spring.r2dbc.password=

spring.sql.init.mode=always
spring.sql.init.platform=all

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

logging.level.org.springframework.data.r2dbc=DEBUG
